# -*- coding: utf-8 -*-
"""ex1_2402cg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSlq7r222K0MjDPEs27OZFBO3yeF-nA2
"""

import math

# Função que calcula o tamanho ou magnitude de um vetor
def calculaTamanho(x, y, z):
    tam = math.sqrt(x * x + y * y + z * z)
    return tam

# Faz a leitura das variáveis do primeiro vetor
print("EXERCÍCIO 01 - COMPUTAÇÃO GRÁFICA")  # print mostra uma mensagem na tela
print("\nDIGITE OS VALORES DO VETOR")  # print mostra uma mensagem na tela
x = float(input("Digite o valor de x: "))  # input é para ler pelo teclado
y = float(input("Digite o valor de y: "))
z = float(input("Digite o valor de z: "))
print("----------------------\n")
print("\nValor de X, Y e Z lidos:", x, y, z)  # print mostra uma mensagem na tela

while True:
    print("1. Calcular o tamanho do vetor")  # print mostra uma mensagem na tela
    print("2. Normalizar o vetor")  # quando a magnitude ou tamanho é igual a 1
    print("3. Adicionar outro vetor")
    print("4. Subtrair outro vetor")
    print("5. Multiplicar por escalar")
    print("6. Dividir por escalar")
    print("7. Produto escalar")
    print("8. Terminar")

    op = int(input("Digite a opção: "))

    # a)
    if op == 1:
        # calcula o tamanho do vetor
        tam = calculaTamanho(x, y, z)
        print("\nO tamanho é igual a", round(tam, 2))
        print("----------------------\n")

    # b)
    elif op == 2:
        # calcula o tamanho do vetor
        tam = calculaTamanho(x, y, z)
        # normaliza o vetor
        if tam == 0:
            print("\nO vetor não pode ser normalizado, pois seu tamanho é zero.")
        else:
            xn = x / tam
            yn = y / tam
            zn = z / tam
            print("\nO vetor normalizado é {:.2f} {:.2f} {:.2f}".format(xn, yn, zn))
        print("----------------------\n")

    # c)
    elif op == 3:
        print("\nDIGITE OS VALORES DO NOVO VETOR")
        x2 = float(input("Digite o valor de x do novo vetor: "))
        y2 = float(input("Digite o valor de y do novo vetor: "))
        z2 = float(input("Digite o valor de z do novo vetor: "))
        # Adiciona os vetores
        x = x + x2
        y = y + y2
        z = z + z2
        print("Resultado da adição: ({:.2f}, {:.2f}, {:.2f})".format(x, y, z))
        print("----------------------\n")

    # d)
    elif op == 4:
        print("\nDIGITE OS VALORES DO VETOR A SER SUBTRAÍDO")
        x2 = float(input("Digite o valor de x do vetor a ser subtraído: "))
        y2 = float(input("Digite o valor de y do vetor a ser subtraído: "))
        z2 = float(input("Digite o valor de z do vetor a ser subtraído: "))
        # Subtrai os vetores
        x = x - x2
        y = y - y2
        z = z - z2
        print("Resultado da subtração: ({:.2f}, {:.2f}, {:.2f})".format(x, y, z))
        print("----------------------\n")

    # e)
    elif op == 5:
        escalar = float(input("Digite o valor do escalar: "))
        # Multiplica o vetor pelo escalar
        x = x * escalar
        y = y * escalar
        z = z * escalar
        print("Resultado da multiplicação por escalar: ({:.2f}, {:.2f}, {:.2f})".format(x, y, z))
        print("----------------------\n")

    # f)
    elif op == 6:
        escalar = float(input("Digite o valor do escalar: "))
        if escalar == 0:
            print("Divisão por zero não é permitida.")
        else:
            # Divide o vetor pelo escalar
            x = x / escalar
            y = y / escalar
            z = z / escalar
            print("Resultado da divisão por escalar: ({:.2f}, {:.2f}, {:.2f})".format(x, y, z))
            print("----------------------\n")

    # g)
    elif op == 7:
        print("\nDIGITE OS VALORES DO VETOR PARA O PRODUTO ESCALAR")
        x2 = float(input("Digite o valor de x do novo vetor: "))
        y2 = float(input("Digite o valor de y do novo vetor: "))
        z2 = float(input("Digite o valor de z do novo vetor: "))
        # Calcula o produto escalar
        produto_escalar = x * x2 + y * y2 + z * z2
        print("Produto escalar: {:.2f}".format(produto_escalar))
        print("----------------------\n")

    # h)
    elif op == 8:
        break  # sai do laço

    else:
        print("Opção inválida!")