# -*- coding: utf-8 -*-
"""exe1cg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkSyXfLxedPYL4lovMORWnoR3U-7hVFc
"""

import math

# Função para calcular o tamanho do vetor
def calcular_tamanho(vetor):
    return math.sqrt(vetor[0]**2 + vetor[1]**2 + vetor[2]**2)

# Função para normalizar o vetor
def normalizar_vetor(vetor):
    tamanho = calcular_tamanho(vetor)
    if tamanho == 0:
        return (0, 0, 0)  # Retorna vetor nulo se o tamanho for 0
    return (vetor[0] / tamanho, vetor[1] / tamanho, vetor[2] / tamanho)

# Função para adicionar dois vetores
def adicionar_vetores(vetor1, vetor2):
    return (vetor1[0] + vetor2[0], vetor1[1] + vetor2[1], vetor1[2] + vetor2[2])

# Função para subtrair dois vetores
def subtrair_vetores(vetor1, vetor2):
    return (vetor1[0] - vetor2[0], vetor1[1] - vetor2[1], vetor1[2] - vetor2[2])

# Função para multiplicar vetor por escalar
def multiplicar_por_escalar(vetor, escalar):
    return (vetor[0] * escalar, vetor[1] * escalar, vetor[2] * escalar)

# Função para dividir vetor por escalar
def dividir_por_escalar(vetor, escalar):
    if escalar == 0:
        return (0, 0, 0)  # Retorna vetor nulo se o escalar for 0
    return (vetor[0] / escalar, vetor[1] / escalar, vetor[2] / escalar)

# Função para calcular o produto escalar
def produto_escalar(vetor1, vetor2):
    return vetor1[0] * vetor2[0] + vetor1[1] * vetor2[1] + vetor1[2] * vetor2[2]

# Leitura do vetor inicial
x = float(input("Digite o valor de x do vetor: "))
y = float(input("Digite o valor de y do vetor: "))
z = float(input("Digite o valor de z do vetor: "))
vetor = (x, y, z)

while True:
    print("\nMenu:")
    print("a) Calcular o tamanho do vetor")
    print("b) Normalizar o vetor")
    print("c) Adicionar outro vetor")
    print("d) Subtrair outro vetor")
    print("e) Multiplicar vetor por escalar")
    print("f) Dividir vetor por escalar")
    print("g) Calcular o produto escalar com outro vetor")
    print("h) Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == 'a':
        tamanho = calcular_tamanho(vetor)
        print(f"Tamanho do vetor: {tamanho}")

    elif opcao == 'b':
        vetor_normalizado = normalizar_vetor(vetor)
        print(f"Vetor normalizado: {vetor_normalizado}")

    elif opcao == 'c':
        x2 = float(input("Digite o valor de x do novo vetor: "))
        y2 = float(input("Digite o valor de y do novo vetor: "))
        z2 = float(input("Digite o valor de z do novo vetor: "))
        novo_vetor = (x2, y2, z2)
        vetor_resultante = adicionar_vetores(vetor, novo_vetor)
        print(f"Resultado da adição: {vetor_resultante}")

    elif opcao == 'd':
        x2 = float(input("Digite o valor de x do novo vetor: "))
        y2 = float(input("Digite o valor de y do novo vetor: "))
        z2 = float(input("Digite o valor de z do novo vetor: "))
        novo_vetor = (x2, y2, z2)
        vetor_resultante = subtrair_vetores(vetor, novo_vetor)
        print(f"Resultado da subtração: {vetor_resultante}")

    elif opcao == 'e':
        escalar = float(input("Digite o valor do escalar: "))
        vetor_resultante = multiplicar_por_escalar(vetor, escalar)
        print(f"Resultado da multiplicação: {vetor_resultante}")

    elif opcao == 'f':
        escalar = float(input("Digite o valor do escalar: "))
        vetor_resultante = dividir_por_escalar(vetor, escalar)
        print(f"Resultado da divisão: {vetor_resultante}")

    elif opcao == 'g':
        x2 = float(input("Digite o valor de x do novo vetor: "))
        y2 = float(input("Digite o valor de y do novo vetor: "))
        z2 = float(input("Digite o valor de z do novo vetor: "))
        novo_vetor = (x2, y2, z2)
        resultado_produto = produto_escalar(vetor, novo_vetor)
        print(f"Produto escalar: {resultado_produto}")

    elif opcao == 'h':
        print("Saindo...")
        break

    else:
        print("Opção inválida! Tente novamente.")