# -*- coding: utf-8 -*-
"""exer_matrizes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTlSB95sG8eBdk1pyMtzaRJ--H-quNQf
"""

import numpy as np

# Definindo as matrizes A e B
A = np.array([[1, 3, 2],
              [4, 7, 6]])  # Matriz A (2x3)

B = np.array([[2, 8],
              [3, 1],
              [5, 9]])  # Matriz B (3x2)

# Verificando se a multiplicação é possível
if len(A[0]) != len(B):
    print("A multiplicação das matrizes não é possível.")
else:
    # Inicializando a matriz C com zeros
    C = np.zeros((2, 2), dtype=int)  # Matriz C (2x2)

    # Multiplicação das matrizes A e B
    for i in range(2):  # Percorre as linhas da matriz A
        for j in range(2):  # Percorre as colunas da matriz B
            for k in range(3):  # Percorre as colunas da matriz A (ou linhas da matriz B)
                C[i][j] += A[i][k] * B[k][j]  # Multiplicação e soma

    # Imprimindo as matrizes A, B e o resultado C
    print("Matriz A:")
    print(A)

    print("\nMatriz B:")
    print(B)

    print("\nResultado da multiplicação (Matriz C):")
    print(C)